version: "3.8"

services:
 adminer-service:
  image: adminer
  restart: unless-stopped
  container_name: adminer
  depends_on:
   - postgres-service
  networks:
   - sinaiapp
  ports:
   - "8080:8080"
  environment:
   - ADMINER_DESIGN=pepa-linha-dark

 fastapi-service:
  build:
   context: .
   dockerfile: Dockerfile
  image: fastapi
  container_name: fastapi
  restart: unless-stopped
  depends_on:
   - postgres-service
  ports:
   - "8000:8000"
  environment:
   - POSTGRES_SERVER=postgres
   - POSTGRES_PORT=${POSTGRES_PORT}
   - POSTGRES_DB=${POSTGRES_DB}
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=Secret$$123
  networks:
   - sinaiapp
  volumes:
   - ".:/app"
  # command: "./startup.sh"

 smtp-service:
  image: axllent/mailpit
  restart: unless-stopped
  container_name: smtp
  networks:
   - sinaiapp
  ports:
   - "8025:8025"
   - "1025:1025"

 postgres-service:
  image: postgres:14
  container_name: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=Secret$$123
   - POSTGRES_DB=fastapi
  networks:
   - sinaiapp
  volumes:
   - sinaiapp_postgres_data:/var/lib/postgresql/data

networks:
 sinaiapp:
volumes:
 sinaiapp_postgres_data:
  external: true
