"""empty message

Revision ID: 5982b325b087
Revises: 52e8e39b2564
Create Date: 2024-09-16 16:19:06.944679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5982b325b087'
down_revision: Union[str, None] = '52e8e39b2564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('churches', 'fullname',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('regions', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=125),
               existing_nullable=True)
    op.alter_column('user_session', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_session', 'token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('regions', 'name',
               existing_type=sa.String(length=125),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('churches', 'fullname',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###