"""empty message

Revision ID: e29e71d1ef67
Revises: 8613f7e04020
Create Date: 2024-09-25 15:53:14.590823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29e71d1ef67'
down_revision: Union[str, None] = '8613f7e04020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'churches', 'cities', ['city_uuid'], ['uuid'])
    op.add_column('regions', sa.Column('country_uuid', sa.UUID(as_uuid=200), nullable=True))
    op.create_foreign_key(None, 'regions', 'countries', ['country_uuid'], ['uuid'])
    op.alter_column('user_session', 'token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.alter_column('user_session', 'firebase_token',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_session', 'firebase_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('user_session', 'token',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'regions', type_='foreignkey')
    op.drop_column('regions', 'country_uuid')
    op.drop_constraint(None, 'churches', type_='foreignkey')
    # ### end Alembic commands ###