"""empty message

Revision ID: f42e8cfb91ba
Revises: a102e7306153
Create Date: 2024-09-13 16:52:45.746961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42e8cfb91ba'
down_revision: Union[str, None] = 'a102e7306153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('church_denominations',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_church_denominations_uuid'), 'church_denominations', ['uuid'], unique=False)
    op.create_table('churches',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('church_denomination_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('fullname', sa.String(length=50), nullable=True),
    sa.Column('city_uuid', sa.UUID(as_uuid=150), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_churches_city_uuid'), 'churches', ['city_uuid'], unique=False)
    op.create_index(op.f('ix_churches_fullname'), 'churches', ['fullname'], unique=True)
    op.create_index(op.f('ix_churches_uuid'), 'churches', ['uuid'], unique=False)
    op.create_table('countries',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_countries_uuid'), 'countries', ['uuid'], unique=False)
    op.create_table('regions',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_regions_uuid'), 'regions', ['uuid'], unique=False)
    op.create_table('roles',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_roles_uuid'), 'roles', ['uuid'], unique=False)
    op.create_table('cities',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('region_uuid', sa.UUID(as_uuid=150), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_uuid'], ['regions.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_cities_region_uuid'), 'cities', ['region_uuid'], unique=False)
    op.create_index(op.f('ix_cities_uuid'), 'cities', ['uuid'], unique=False)
    op.create_table('posts',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('church_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_uuid'], ['churches.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_posts_uuid'), 'posts', ['uuid'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('city_uuid', sa.UUID(as_uuid=150), nullable=True),
    sa.Column('country_uuid', sa.UUID(as_uuid=150), nullable=True),
    sa.Column('avatar', sa.UUID(as_uuid=150), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=125), nullable=True),
    sa.Column('gender', sa.String(length=12), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_uuid'], ['cities.uuid'], ),
    sa.ForeignKeyConstraint(['country_uuid'], ['countries.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_address'), 'users', ['address'], unique=False)
    op.create_index(op.f('ix_users_city_uuid'), 'users', ['city_uuid'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    op.create_table('church_users',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('church_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('user_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('role_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_uuid'], ['churches.uuid'], ),
    sa.ForeignKeyConstraint(['role_uuid'], ['roles.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_church_users_position'), 'church_users', ['position'], unique=False)
    op.create_index(op.f('ix_church_users_uuid'), 'church_users', ['uuid'], unique=False)
    op.create_table('files',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('user_uuid', sa.UUID(as_uuid=150), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=150), nullable=True),
    sa.Column('ext', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=20), nullable=True),
    sa.Column('active', sa.String(length=125), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_files_active'), 'files', ['active'], unique=False)
    op.create_index(op.f('ix_files_uuid'), 'files', ['uuid'], unique=False)
    op.create_table('user_session',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('user_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('church_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('firebase_token', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_uuid'], ['churches.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_user_session_uuid'), 'user_session', ['uuid'], unique=False)
    op.create_table('posts_files',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('post_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('file_uuid', sa.UUID(as_uuid=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_uuid'], ['files.uuid'], ),
    sa.ForeignKeyConstraint(['post_uuid'], ['posts.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_posts_files_uuid'), 'posts_files', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_files_uuid'), table_name='posts_files')
    op.drop_table('posts_files')
    op.drop_index(op.f('ix_user_session_uuid'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_files_uuid'), table_name='files')
    op.drop_index(op.f('ix_files_active'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_church_users_uuid'), table_name='church_users')
    op.drop_index(op.f('ix_church_users_position'), table_name='church_users')
    op.drop_table('church_users')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_city_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_address'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_posts_uuid'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_cities_uuid'), table_name='cities')
    op.drop_index(op.f('ix_cities_region_uuid'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_roles_uuid'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_regions_uuid'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_countries_uuid'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_churches_uuid'), table_name='churches')
    op.drop_index(op.f('ix_churches_fullname'), table_name='churches')
    op.drop_index(op.f('ix_churches_city_uuid'), table_name='churches')
    op.drop_table('churches')
    op.drop_index(op.f('ix_church_denominations_uuid'), table_name='church_denominations')
    op.drop_table('church_denominations')
    # ### end Alembic commands ###